PREFIX ontology:<http://www.semanticweb.org/aleca/ontologies/2019/10/untitled-ontology-10#>
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?lat ?lon
WHERE {
    ?shop a ontology:Shop .
    ?shop ontology:PoiName ?name .
    ?shop ontology:Latitude ?lat .
    ?shop ontology:Longitude ?lon .
    ?shop ontology:hasShopEnum ontology:S_Bikes .
}


